### ISSUE TITLE
[screens] - Fund Wallet

### ISSUE THREAD

**Issue by karliatto** [Learn-by-doing/lightning-extension#3]
This screen shows a QR code with a bitcoind address so the user can send some funds that later can be used in lightning network

![02-fund-wallet](https://user-images.githubusercontent.com/5362163/48015817-48241380-e12a-11e8-8bcd-181fad2fbb03.png)

**Comment by chill117** [comment]
No longer needed because we will rely on the Lightning App's GUI for this.
